"""
Phase 4 — Broker adapter interface.

BrokerAdapter is a structural Protocol (typing.Protocol) so any class that
implements the five required async methods satisfies it without inheritance.
Both PaperBrokerAdapter and ZerodhaKiteAdapter implement this interface.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Protocol, runtime_checkable


# ---------------------------------------------------------------------------
# Shared data classes
# ---------------------------------------------------------------------------

@dataclass
class OrderRequest:
    symbol:           str
    exchange:         str   # NSE | BSE
    instrument_type:  str   # CE | PE | EQ
    transaction_type: str   # BUY | SELL
    order_type:       str   # MARKET | LIMIT | SL | SL-M
    product:          str   # MIS | NRML | CNC
    qty:              int
    price:            float = 0.0
    trigger_price:    float = 0.0
    # UUID generated by caller; used for idempotency (4.6)
    client_order_id:  str = field(default_factory=lambda: str(uuid.uuid4()))


@dataclass
class OrderResult:
    client_order_id: str
    status:          str   # PLACED | REJECTED
    broker_order_id: str = ""
    message:         str = ""
    raw_response:    dict = field(default_factory=dict)


@dataclass
class Position:
    symbol:        str
    qty:           int
    avg_price:     float
    pnl:           float
    product:       str
    instrument_type: str = "EQ"


@dataclass
class Order:
    broker_order_id:  str
    client_order_id:  str
    symbol:           str
    transaction_type: str
    qty:              int
    price:            float
    status:           str   # PENDING | PLACED | FILLED | REJECTED | CANCELLED
    filled_qty:       int   = 0
    average_price:    float = 0.0


# ---------------------------------------------------------------------------
# Protocol
# ---------------------------------------------------------------------------

@runtime_checkable
class BrokerAdapter(Protocol):
    """
    Structural protocol that both PaperBrokerAdapter and ZerodhaKiteAdapter
    must satisfy.  All methods are async.
    """

    async def place_order(self, req: OrderRequest) -> OrderResult: ...

    async def modify_order(
        self, order_id: str, price: float, qty: int
    ) -> OrderResult: ...

    async def cancel_order(self, order_id: str) -> OrderResult: ...

    async def get_positions(self) -> list[Position]: ...

    async def get_orders(self) -> list[Order]: ...
